server:
  port: 8000
  servlet:
    session:
      timeout: 600000
spring:
  # 配置写数据库信息
  datasource:
    url: jdbc:mysql://rm-uf6rr8230awt5kuku.mysql.rds.aliyuncs.com:3306/hello?characterEncoding=utf8&useSSL=false
    username: helloadmin
    password: Lawosi123223
    driver-class-name: com.mysql.jdbc.Driver
    # 配置Druid
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 200
    minIdle: 20
    maxActive: 200
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    #filters: stat,wall,log4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
  # 配置jpa
  jpa:
    database: MySQL
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  # 配置spring session使用redis存储
#  session:
#    store-type: redis
#  redis:
#    host: localhost
#    port: 6379
#    database: 0
file_store_path: /opt/upload/